# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        PORT : '1234'
    image: ift6758/serving:latest
    ports:
      - 1234:1234
    environment:
      - COMET_API_KEY=${COMET_API_KEY}

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
      args:
        STREAMLIT_PORT : '2345'
        STREAMLIT_ADDRESS : '0.0.0.0'
    image: ift6758/streamlit:latest
    ports:
      - 2345:2345
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      - DATA_FOLDER=/code/data_assets_frontend_app/
      - BACKEND_ADDRESS=serving
      - BACKEND_PORT=1234
      

     
