defaults:
  - _self_
  - data_pipeline:
      - feature_engineering # will resolve to content in ./data_pipeline/feature_engineering.yaml
      - data_preprocessing # will resolve to content in ./data_pipeline/data_preprocessing.yaml
  - model : logistic_regression # will resolve to content in ./model/logistic_regression.yaml

# provide file path to raw data FROM ROOT DIRECTORY specified by env var DATA_FOLDER in .env file
raw_train_data_path: 2016_2020_data_150cd5075.csv