defaults:
  - _self_
  - data_pipeline:
      - feature_engineering # will resolve to content in ./data_pipeline/feature_engineering.yaml
      - data_preprocessing # will resolve to content in ./data_pipeline/data_preprocessing.yaml
  - model : logistic_regression # will resolve to content in ./model/logistic_regression.yaml
  - comet_ml : conf # will resolve to content in ./comet_ml/comet_ml.yaml

# provide file path to raw data 
# path must be relative to ROOT DIRECTORY specified by env var DATA_FOLDER in .env file
raw_train_data_path: json_scrapper_output/data_2016_2020_7ecc5b717675.csv

# version of the Feature Engineering pipeline
# will determine in which subdir of data/feature_engineering_outpout/ the engineered data will be saved
feature_engineering_version: 1

# path to load feature-engineered data from (avoid to recompute all proocessing That can be long)
# path must be relative to ROOT DIRECTORY specified by env var DATA_FOLDER in .env file
# if None, feature engineering will be recomputed
load_engineered_data_from: data/processed/feature_engineered_data_v1.csv # null

# TODO : PROVIDE A KEY TO RESUME TRAINING FROM A PREVIOUS CHECKPOINT/COMET EXPERIMENT
# resume_from_

