defaults:
  - _self_
  - data_pipeline:
      - feature_engineering # will resolve to content in ./data_pipeline/feature_engineering.yaml
      - data_preprocessing # will resolve to content in ./data_pipeline/data_preprocessing.yaml
      - feature_selection # will resolve to content in ./data_pipeline/feature_selection.yaml
  - model : xgboost # xgboost logistic_regression | will resolve to content in ./model/logistic_regression.yaml

# TODO : PROVIDE A KEY TO RESUME TRAINING FROM A PREVIOUS CHECKPOINT/COMET EXPERIMENT
# resume_from_

holdout_test: False
BASELINE_SUBSET_TO_ANGLE_DIST : False
USE_CROSS_VALIDATION : False
USE_SAMPLE_WEIGHTS : True # for class imbal ance

COMET_EXPERIEMENT_TAGS:
  - 'xgboost_test_eval'

RESUME_FROM_MODEL_CHECKPOINT: null # ABSOLUTE Path to pickle file | json file if XGBoost
JUST_EVALUATE: False # Only evaluate on Val OR Test set
LOG_DATA_SPLITS_BEFORE_TRAIN : True # Log data splits before training
LOG_TRAINED_MODEL : True # Log model to comet