model_type: MLPClassifier

hidden_layer_sizes:
  - 64           
  - 32
  - 0
  - 32
learning_rate_init: 0.001
alpha: 0.0001
activation: relu
solver: adam
batch_size: 32
shuffle: True
early_stopping: True
n_iter_no_change: 20
epsilon: 1e-08

